python extract_scene.py active_projects/eola2/cramer.py ThreeDCoordinatesAsVolumes -pl
python extract_scene.py active_projects/eola2/determinant_puzzle.py WorkOutNumerically -pl
python extract_scene.py active_projects/eop/chapter1/all_sequences.py ShuffleThroughAllSequences -pl
python extract_scene.py active_projects/eop/chapter1/morph_brick_row_into_histogram.py GenericMorphBrickRowIntoHistogram -pl
python extract_scene.py active_projects/eop/chapter1/show_uncertainty_darts.py ShowUncertaintyDarts -pl
python extract_scene.py active_projects/eop/chapter1/show_uncertainty_dice.py ShowUncertaintyDice -pl
python extract_scene.py active_projects/eop/chapter1/various_intro_visuals.py TwoDiceTableScene -pl
python extract_scene.py active_projects/eop/combinations.py InitialFiveChooseThreeExample -pl
python extract_scene.py active_projects/eop/combinations.py:# class DifferentWaysToThinkAboutNChooseK -pl
python extract_scene.py active_projects/eop/combinations.py:# class GroupsOf6 -pl
python extract_scene.py active_projects/eop/combinations.py:# class GroupsOf7 -pl
python extract_scene.py active_projects/eop/combinations.py IntroducePascalsTriangle -pl
python extract_scene.py active_projects/eop/pascal.py SimplePascal -pl
python extract_scene.py active_projects/eop/pascal.py PascalNetScene -pl
python extract_scene.py active_projects/eop/pascal.py RescaledPascalNetScene -pl
python extract_scene.py active_projects/quaternions.py IntroduceHamilton -pl
python extract_scene.py active_projects/quaternions.py QuaternionHistory -pl
python extract_scene.py for_3b1b_videos/common_scenes.py PatreonThanks -pl
python extract_scene.py for_3b1b_videos/common_scenes.py ExternallyAnimatedScene -pl
python extract_scene.py old_projects/256.py MainBreakdown -pl
python extract_scene.py old_projects/basel/basel.py EarthScene -pl
python extract_scene.py old_projects/basel/basel.py ThumbnailScene -pl
python extract_scene.py old_projects/basel/basel.py RightAnglesOverlay -pl
python extract_scene.py old_projects/basel/basel2.py IntroduceScreen -pl
python extract_scene.py old_projects/basel/basel2.py MathologerVideoWrapper -pl
python extract_scene.py old_projects/basel/basel2.py Credits -pl
python extract_scene.py old_projects/bell.py SecondVideoWrapper -pl
python extract_scene.py old_projects/bell.py AngleToProbabilityChart -pl
python extract_scene.py old_projects/bell.py VennDiagramProofByContradiction -pl
python extract_scene.py old_projects/bell.py PonderingPiCreature -pl
python extract_scene.py old_projects/borsuk.py FromPreviousTopologyVideo -pl
python extract_scene.py old_projects/borsuk.py ExternallyAnimatedScene -pl
python extract_scene.py old_projects/borsuk.py WriteWords -pl
python extract_scene.py old_projects/borsuk.py PointsIn3D -pl
python extract_scene.py old_projects/borsuk.py WritePointCoordinates -pl
python extract_scene.py old_projects/borsuk.py GeneralizeBorsukUlam -pl
python extract_scene.py old_projects/borsuk.py WhatThisMappingActuallyLooksLikeWords -pl
python extract_scene.py old_projects/borsuk.py CircleToSphereToQMarks -pl
python extract_scene.py old_projects/borsuk.py RotatingThreeDSphereProjection -pl
python extract_scene.py old_projects/brachistochrone/curves.py BrachistochroneWordSliding -pl
python extract_scene.py old_projects/brachistochrone/curves.py MinimalPotentialEnergy -pl
python extract_scene.py old_projects/brachistochrone/curves.py ThetaTInsteadOfXY -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py TracePicture -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py JohannThinksHeIsBetter -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py NewtonVsJohann -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py JohannThinksOfFermat -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py MathematiciansOfEurope -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py OldNewtonIsDispleased -pl
python extract_scene.py old_projects/brachistochrone/drawing_images.py NewtonConsideredEveryoneBeneathHim -pl
python extract_scene.py old_projects/brachistochrone/misc.py PhysicalIntuition -pl
python extract_scene.py old_projects/brachistochrone/misc.py TimeLine -pl
python extract_scene.py old_projects/brachistochrone/misc.py StayedUpAllNight -pl
python extract_scene.py old_projects/brachistochrone/misc.py ThetaTGraph -pl
python extract_scene.py old_projects/brachistochrone/misc.py SolutionsToTheBrachistochrone -pl
python extract_scene.py old_projects/brachistochrone/misc.py VideoLayout -pl
python extract_scene.py old_projects/brachistochrone/misc.py ShortestPathProblem -pl
python extract_scene.py old_projects/brachistochrone/misc.py MathBetterThanTalking -pl
python extract_scene.py old_projects/brachistochrone/misc.py DetailsOfProofBox -pl
python extract_scene.py old_projects/brachistochrone/misc.py TalkedAboutSnellsLaw -pl
python extract_scene.py old_projects/brachistochrone/misc.py YetAnotherMarkLevi -pl
python extract_scene.py old_projects/brachistochrone/multilayered.py MultilayeredScene -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py Intro -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py IntroduceSteve -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py ShowTweets -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py LetsBeHonest -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py WhatIsTheBrachistochrone -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py DisectBrachistochroneWord -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py OneSolutionTwoInsights -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py CircleOfIdeas -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py FermatsPrincipleStatement -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py VideoProgression -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py BalanceCompetingFactors -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py Challenge -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py NarratorInterjection -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py ThisCouldBeTheEnd -pl
python extract_scene.py old_projects/brachistochrone/wordplay.py CondensedVersion -pl
python extract_scene.py old_projects/complex_multiplication_article.py DrawSolutionsToZToTheNEqualsW -pl
python extract_scene.py old_projects/complex_multiplication_article.py DrawComplexAngleAndMagnitude -pl
python extract_scene.py old_projects/counting_in_binary.py OverHand -pl
python extract_scene.py old_projects/counting_in_binary.py CountTo1023 -pl
python extract_scene.py old_projects/counting_in_binary.py ShowReadingRule -pl
python extract_scene.py old_projects/counting_in_binary.py ShowIncrementRule -pl
python extract_scene.py old_projects/counting_in_binary.py MindFindsShortcuts -pl
python extract_scene.py old_projects/counting_in_binary.py FinishCountingExampleSentence -pl
python extract_scene.py old_projects/counting_in_binary.py Question -pl
python extract_scene.py old_projects/counting_in_binary.py TwoHandStatement -pl
python extract_scene.py old_projects/counting_in_binary.py WithToes -pl
python extract_scene.py old_projects/crypto.py ListOfAttributes -pl
python extract_scene.py old_projects/crypto.py UnknownAuthor -pl
python extract_scene.py old_projects/crypto.py ListRecentCurrencies -pl
python extract_scene.py old_projects/crypto.py UnderlyingSystemVsUserFacing -pl
python extract_scene.py old_projects/crypto.py TryGuessingDigitalSignature -pl
python extract_scene.py old_projects/crypto.py BitcoinIsALedger -pl
python extract_scene.py old_projects/crypto.py BigDifferenceBetweenLDAndCryptocurrencies -pl
python extract_scene.py old_projects/crypto.py IntroduceSHA256 -pl
python extract_scene.py old_projects/crypto.py CompareBlockTimes -pl
python extract_scene.py old_projects/crypto.py BlockRewards -pl
python extract_scene.py old_projects/crypto.py ShowGeometricSum -pl
python extract_scene.py old_projects/crypto.py ShowManyExchanges -pl
python extract_scene.py old_projects/dandelin.py EccentricityForSlicedConed -pl
python extract_scene.py old_projects/dandelin.py ShowSegmentSplit -pl
python extract_scene.py old_projects/dandelin.py NameDandelin -pl
python extract_scene.py old_projects/dandelin.py LockhartQuote -pl
python extract_scene.py old_projects/div_curl.py IntroduceVectorField -pl
python extract_scene.py old_projects/div_curl.py ShowTwoPopulations -pl
python extract_scene.py old_projects/div_curl.py ThoughtsOnAds -pl
python extract_scene.py old_projects/efvgt.py HomomophismPreview -pl
python extract_scene.py old_projects/efvgt.py ThisIsAVeryGeneralIdea -pl
python extract_scene.py old_projects/efvgt.py SchizophrenicNumbers -pl
python extract_scene.py old_projects/eoc/chapter10.py HigherTermsDontMessUpLowerTerms -pl
python extract_scene.py old_projects/eoc/chapter10.py EachTermControlsOneDerivative -pl
python extract_scene.py old_projects/eoc/chapter10.py ConvergenceExample -pl
python extract_scene.py old_projects/eoc/chapter2.py FathersOfCalculus -pl
python extract_scene.py old_projects/eoc/chapter2.py IntroduceCar -pl
python extract_scene.py old_projects/eoc/chapter2.py SnapshotOfACar -pl
python extract_scene.py old_projects/eoc/chapter2.py CompareTwoTimes -pl
python extract_scene.py old_projects/eoc/chapter2.py SidestepParadox -pl
python extract_scene.py old_projects/eoc/chapter2.py DefineTrueDerivative -pl
python extract_scene.py old_projects/eoc/chapter3.py ContrastAbstractAndConcrete -pl
python extract_scene.py old_projects/eoc/chapter3.py ShowCubeDVIn3D -pl
python extract_scene.py old_projects/eoc/chapter3.py PowerRuleAlgebra -pl
python extract_scene.py old_projects/eoc/chapter4.py ShoveXSquaredInSine -pl
python extract_scene.py old_projects/eoc/chapter4.py GeneralizeChainRule -pl
python extract_scene.py old_projects/eoc/chapter8.py ConstantVelocityCar -pl
python extract_scene.py old_projects/eoc/chapter8.py PiecewiseConstantCar -pl
python extract_scene.py old_projects/eoc/chapter8.py CarJourneyApproximation -pl
python extract_scene.py old_projects/eoc/footnote.py Footnote -pl
python extract_scene.py old_projects/eoc/footnote.py SecondDerivativeAsAcceleration -pl
python extract_scene.py old_projects/eola/chapter0.py UpcomingSeriesOfVidoes -pl
python extract_scene.py old_projects/eola/chapter0.py AboutLinearAlgebra -pl
python extract_scene.py old_projects/eola/chapter0.py NumericVsGeometric -pl
python extract_scene.py old_projects/eola/chapter0.py NumericToComputations -pl
python extract_scene.py old_projects/eola/chapter0.py LinAlgPyramid -pl
python extract_scene.py old_projects/eola/chapter0.py IntimidatingProf -pl
python extract_scene.py old_projects/eola/chapter0.py SineApproximations -pl
python extract_scene.py old_projects/eola/chapter0.py LooseConnectionToTriangles -pl
python extract_scene.py old_projects/eola/chapter0.py PhysicsExample -pl
python extract_scene.py old_projects/eola/chapter0.py LinearAlgebraIntuitions -pl
python extract_scene.py old_projects/eola/chapter0.py MatricesAre -pl
python extract_scene.py old_projects/eola/chapter0.py MatrixMultiplicationIs -pl
python extract_scene.py old_projects/eola/chapter0.py DeterminantsAre -pl
python extract_scene.py old_projects/eola/chapter0.py ProfessorsTry -pl
python extract_scene.py old_projects/eola/chapter0.py ResourceForTeachers -pl
python extract_scene.py old_projects/eola/chapter0.py AboutPacing -pl
python extract_scene.py old_projects/eola/chapter0.py DifferingBackgrounds -pl
python extract_scene.py old_projects/eola/chapter0.py PauseAndPonder -pl
python extract_scene.py old_projects/eola/chapter1.py DifferentConceptions -pl
python extract_scene.py old_projects/eola/chapter1.py ThreeDVectorField -pl
python extract_scene.py old_projects/eola/chapter1.py HelpsToHaveOneThought -pl
python extract_scene.py old_projects/eola/chapter1.py HowIWantYouToThinkAboutVectors -pl
python extract_scene.py old_projects/eola/chapter1.py ListsOfNumbersAddOn -pl
python extract_scene.py old_projects/eola/chapter1.py LabeledThreeDVector -pl
python extract_scene.py old_projects/eola/chapter1.py WriteZ -pl
python extract_scene.py old_projects/eola/chapter1.py Write3DVector -pl
python extract_scene.py old_projects/eola/chapter1.py AddingNumbersOnNumberLine -pl
python extract_scene.py old_projects/eola/chapter1.py MultiplicationByANumberIntro -pl
python extract_scene.py old_projects/eola/chapter1.py ItDoesntMatterWhich -pl
python extract_scene.py old_projects/eola/chapter1.py DataAnalyst -pl
python extract_scene.py old_projects/eola/chapter1.py CodingMathyAnimation -pl
python extract_scene.py old_projects/eola/chapter10.py ShowComments -pl
python extract_scene.py old_projects/eola/chapter10.py ManyPrerequisites -pl
python extract_scene.py old_projects/eola/chapter10.py ThreeDRotationTitle -pl
python extract_scene.py old_projects/eola/chapter10.py ThreeDShowRotation -pl
python extract_scene.py old_projects/eola/chapter10.py ThreeDShowRotationWithEigenvector -pl
python extract_scene.py old_projects/eola/chapter10.py EigenvectorToAxisOfRotation -pl
python extract_scene.py old_projects/eola/chapter10.py EigenvalueOne -pl
python extract_scene.py old_projects/eola/chapter10.py SymbolicEigenvectors -pl
python extract_scene.py old_projects/eola/chapter10.py LineOfReasoning -pl
python extract_scene.py old_projects/eola/chapter10.py DefineDiagonalMatrix -pl
python extract_scene.py old_projects/eola/chapter10.py RepeatedMultiplicationInAction -pl
python extract_scene.py old_projects/eola/chapter10.py RepeatedMultilpicationOfMatrices -pl
python extract_scene.py old_projects/eola/chapter11.py HigherDimensionalVectorsNumerically -pl
python extract_scene.py old_projects/eola/chapter11.py AskAbout4DPhysicsStudent -pl
python extract_scene.py old_projects/eola/chapter11.py WhatIsSpace -pl
python extract_scene.py old_projects/eola/chapter11.py FunctionGraphScene -pl
python extract_scene.py old_projects/eola/chapter11.py AddVectorsCoordinateByCoordinate -pl
python extract_scene.py old_projects/eola/chapter11.py ScaleVectorByCoordinates -pl
python extract_scene.py old_projects/eola/chapter11.py DerivativeIsLinear -pl
python extract_scene.py old_projects/eola/chapter11.py PolynomialsHaveArbitrarilyLargeDegree -pl
python extract_scene.py old_projects/eola/chapter11.py GeneneralPolynomialCoordinates -pl
python extract_scene.py old_projects/eola/chapter11.py SimplePolynomialCoordinates -pl
python extract_scene.py old_projects/eola/chapter11.py IntroducePolynomialSpace -pl
python extract_scene.py old_projects/eola/chapter11.py CompareTermsInLinearAlgebraToFunction -pl
python extract_scene.py old_projects/eola/chapter11.py YouAsAMathematician -pl
python extract_scene.py old_projects/eola/chapter11.py ShowVectorSpaces -pl
python extract_scene.py old_projects/eola/chapter11.py ToolsOfLinearAlgebra -pl
python extract_scene.py old_projects/eola/chapter11.py MathematicianSpeakingToAll -pl
python extract_scene.py old_projects/eola/chapter11.py ListAxioms -pl
python extract_scene.py old_projects/eola/chapter11.py AxiomsAreInterface -pl
python extract_scene.py old_projects/eola/chapter11.py VectorSpaceOfPiCreatures -pl
python extract_scene.py old_projects/eola/chapter11.py MathematicianDoesntHaveToThinkAboutThat -pl
python extract_scene.py old_projects/eola/chapter11.py WhatIsThree -pl
python extract_scene.py old_projects/eola/chapter11.py AbstractionIsThePrice -pl
python extract_scene.py old_projects/eola/chapter2.py WhatIfWeChoseADifferentBasis -pl
python extract_scene.py old_projects/eola/chapter2.py NameLinearCombinations -pl
python extract_scene.py old_projects/eola/chapter2.py DefineSpan -pl
python extract_scene.py old_projects/eola/chapter2.py VectorsVsPoints -pl
python extract_scene.py old_projects/eola/chapter2.py HowToThinkVectorsVsPoint -pl
python extract_scene.py old_projects/eola/chapter2.py IntroduceThreeDSpan -pl
python extract_scene.py old_projects/eola/chapter2.py AskAboutThreeDSpan -pl
python extract_scene.py old_projects/eola/chapter2.py ThreeDVectorSpan -pl
python extract_scene.py old_projects/eola/chapter2.py LinearCombinationOfThreeVectors -pl
python extract_scene.py old_projects/eola/chapter2.py VaryingLinearCombinationOfThreeVectors -pl
python extract_scene.py old_projects/eola/chapter2.py LinearCombinationOfThreeVectorsText -pl
python extract_scene.py old_projects/eola/chapter2.py ThirdVectorOnSpanOfFirstTwo -pl
python extract_scene.py old_projects/eola/chapter2.py ThirdVectorOutsideSpanOfFirstTwo -pl
python extract_scene.py old_projects/eola/chapter2.py SpanCasesWords -pl
python extract_scene.py old_projects/eola/chapter2.py LinearDependentWords -pl
python extract_scene.py old_projects/eola/chapter2.py LinearDependentEquations -pl
python extract_scene.py old_projects/eola/chapter2.py AlternateDefOfLinearlyDependent -pl
python extract_scene.py old_projects/eola/chapter2.py TechnicalDefinitionOfBasis -pl
python extract_scene.py old_projects/eola/chapter3.py DescribeTransformation -pl
python extract_scene.py old_projects/eola/chapter3.py LookToWordLinear -pl
python extract_scene.py old_projects/eola/chapter3.py ToThePedants -pl
python extract_scene.py old_projects/eola/chapter3.py NowWithoutWatching -pl
python extract_scene.py old_projects/eola/chapter3.py DeduceResultWithGeneralCoordinates -pl
python extract_scene.py old_projects/eola/chapter3.py OtherWayAround -pl
python extract_scene.py old_projects/eola/chapter3.py FinalSlide -pl
python extract_scene.py old_projects/eola/chapter3.py TransformationsAreFunctions -pl
python extract_scene.py old_projects/eola/chapter3.py TryingToVisualizeFourDimensions -pl
python extract_scene.py old_projects/eola/chapter3.py ForgetAboutGraphs -pl
python extract_scene.py old_projects/eola/chapter3.py ShowGridCreation -pl
python extract_scene.py old_projects/eola/chapter4.py MatrixToBlank -pl
python extract_scene.py old_projects/eola/chapter4.py ExplainWhyItsMatrixMultiplication -pl
python extract_scene.py old_projects/eola/chapter4.py AskAboutCommutativity -pl
python extract_scene.py old_projects/eola/chapter4.py AskAssociativityQuestion -pl
python extract_scene.py old_projects/eola/chapter4.py ExplanationTrumpsProof -pl
python extract_scene.py old_projects/eola/chapter5.py NextFewVideos -pl
python extract_scene.py old_projects/eola/chapter5.py NegativeDeterminant -pl
python extract_scene.py old_projects/eola/chapter5.py FlipSpaceOver -pl
python extract_scene.py old_projects/eola/chapter5.py RandyThinking -pl
python extract_scene.py old_projects/eola/chapter5.py ThinkAboutFlippingPaper -pl
python extract_scene.py old_projects/eola/chapter5.py DeterminantGraphForRotatingIHat -pl
python extract_scene.py old_projects/eola/chapter5.py Transforming3DCube -pl
python extract_scene.py old_projects/eola/chapter5.py NameParallelepiped -pl
python extract_scene.py old_projects/eola/chapter5.py DeterminantIsVolumeOfParallelepiped -pl
python extract_scene.py old_projects/eola/chapter5.py Degenerate3DTransformation -pl
python extract_scene.py old_projects/eola/chapter5.py WriteZeroDeterminant -pl
python extract_scene.py old_projects/eola/chapter5.py OrientationReversing3DTransformation -pl
python extract_scene.py old_projects/eola/chapter5.py RightHandRule -pl
python extract_scene.py old_projects/eola/chapter5.py TwoDDeterminantFormula -pl
python extract_scene.py old_projects/eola/chapter5.py ThreeDDetFormula -pl
python extract_scene.py old_projects/eola/chapter5.py ProductProperty -pl
python extract_scene.py old_projects/eola/chapter6.py ListTerms -pl
python extract_scene.py old_projects/eola/chapter6.py PuntToSoftware -pl
python extract_scene.py old_projects/eola/chapter6.py UsefulnessOfMatrices -pl
python extract_scene.py old_projects/eola/chapter6.py CircuitDiagram -pl
python extract_scene.py old_projects/eola/chapter6.py StockPrices -pl
python extract_scene.py old_projects/eola/chapter6.py MachineLearningNetwork -pl
python extract_scene.py old_projects/eola/chapter6.py ComplicatedSystem -pl
python extract_scene.py old_projects/eola/chapter6.py SystemOfEquations -pl
python extract_scene.py old_projects/eola/chapter6.py ThinkAboutWhatsHappening -pl
python extract_scene.py old_projects/eola/chapter6.py SystemOfTwoEquationsTwoUnknowns -pl
python extract_scene.py old_projects/eola/chapter6.py TwoDInverseFormula -pl
python extract_scene.py old_projects/eola/chapter6.py SymbolicInversion -pl
python extract_scene.py old_projects/eola/chapter6.py OneUniqueSolution -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDTransformXToV -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDTransformAndReverse -pl
python extract_scene.py old_projects/eola/chapter6.py DetNEZeroRule -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDInverseRule -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDApplyReverseToV -pl
python extract_scene.py old_projects/eola/chapter6.py PrepareForRank -pl
python extract_scene.py old_projects/eola/chapter6.py DefineRank -pl
python extract_scene.py old_projects/eola/chapter6.py DefineColumnSpace -pl
python extract_scene.py old_projects/eola/chapter6.py ColumnsRepresentBasisVectors -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDOntoPlane -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDOntoLine -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDOntoPoint -pl
python extract_scene.py old_projects/eola/chapter6.py FullRankWords -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDColumnsDontSpan -pl
python extract_scene.py old_projects/eola/chapter6.py NameColumnSpace -pl
python extract_scene.py old_projects/eola/chapter6.py RankNumber -pl
python extract_scene.py old_projects/eola/chapter6.py NameFullRank -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDNullSpaceIsLine -pl
python extract_scene.py old_projects/eola/chapter6.py ThreeDNullSpaceIsPlane -pl
python extract_scene.py old_projects/eola/chapter6.py NullSpaceOffsetRule -pl
python extract_scene.py old_projects/eola/chapter7.py ShowNumericalDotProduct -pl
python extract_scene.py old_projects/eola/chapter7.py Symbolic2To1DTransform -pl
python extract_scene.py old_projects/eola/chapter7.py RecommendChapter3 -pl
python extract_scene.py old_projects/eola/chapter7.py OkayToIgnoreFormalProperties -pl
python extract_scene.py old_projects/eola/chapter7.py FormalVsVisual -pl
python extract_scene.py old_projects/eola/chapter7.py TwoDOneDMatrixMultiplication -pl
python extract_scene.py old_projects/eola/chapter7.py AssociationBetweenMatricesAndVectors -pl
python extract_scene.py old_projects/eola/chapter7.py SomeKindOfConnection -pl
python extract_scene.py old_projects/eola/chapter7.py ImagineYouDontKnowThis -pl
python extract_scene.py old_projects/eola/chapter7.py ProjectionFunctionSymbol -pl
python extract_scene.py old_projects/eola/chapter7.py AskAboutProjectionMatrix -pl
python extract_scene.py old_projects/eola/chapter7.py UHatIsTransformInDisguise -pl
python extract_scene.py old_projects/eola/chapter7.py TwoDOneDTransformationSeparateSpace -pl
python extract_scene.py old_projects/eola/chapter7.py RememberGraphDuality -pl
python extract_scene.py old_projects/eola/chapter7.py LooseDualityDescription -pl
python extract_scene.py old_projects/eola/chapter7.py WhatTheVectorWantsToBe -pl
python extract_scene.py old_projects/eola/chapter8.py ListSteps -pl
python extract_scene.py old_projects/eola/chapter8.py ContrastDotAndCross -pl
python extract_scene.py old_projects/eola/chapter8.py PrereqDeterminant -pl
python extract_scene.py old_projects/eola/chapter8.py ThreeDShowParallelogramAndCrossProductVector -pl
python extract_scene.py old_projects/eola/chapter8.py WriteAreaOfParallelogram -pl
python extract_scene.py old_projects/eola/chapter8.py WriteCrossProductProperties -pl
python extract_scene.py old_projects/eola/chapter8.py LabelingExampleVectors -pl
python extract_scene.py old_projects/eola/chapter8.py ThreeDTwoPossiblePerpendicularVectors -pl
python extract_scene.py old_projects/eola/chapter8.py ThreeDCrossProductExample -pl
python extract_scene.py old_projects/eola/chapter8.py ShowCrossProductFormula -pl
python extract_scene.py old_projects/eola/chapter8.py DeterminantTrick -pl
python extract_scene.py old_projects/eola/chapter8.py CrossAndDualWords -pl
python extract_scene.py old_projects/eola/chapter8p2.py CrossProductSymbols -pl
python extract_scene.py old_projects/eola/chapter8p2.py BruteForceVerification -pl
python extract_scene.py old_projects/eola/chapter8p2.py Prerequisites -pl
python extract_scene.py old_projects/eola/chapter8p2.py DotProductToTransformSymbol -pl
python extract_scene.py old_projects/eola/chapter8p2.py MathematicalWild -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeStepPlan -pl
python extract_scene.py old_projects/eola/chapter8p2.py DefineDualTransform -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDTripleCrossProduct -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDMovingVariableVector -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDMovingVariableVectorWithCrossShowing -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDDotProductProjection -pl
python extract_scene.py old_projects/eola/chapter8p2.py DotProductWords -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDProjectToPerpendicular -pl
python extract_scene.py old_projects/eola/chapter8p2.py GeometricVolumeWords -pl
python extract_scene.py old_projects/eola/chapter8p2.py WriteXYZ -pl
python extract_scene.py old_projects/eola/chapter8p2.py ThreeDDotProductWithCross -pl
python extract_scene.py old_projects/eola/chapter8p2.py CrossVectorEmphasisWords -pl
python extract_scene.py old_projects/eola/chapter9.py NameCoordinateSystem -pl
python extract_scene.py old_projects/eola/chapter9.py FeelsBackwards -pl
python extract_scene.py old_projects/eola/chapter9.py WorkOutInverseComputation -pl
python extract_scene.py old_projects/eola/chapter9.py SummarizeTranslationProcess -pl
python extract_scene.py old_projects/eola/chapter9.py Prerequisites -pl
python extract_scene.py old_projects/eola/chapter9.py HowToTranslateAMatrix -pl
python extract_scene.py old_projects/eola/footnote.py SymbolicThreeDTransform -pl
python extract_scene.py old_projects/eola/footnote.py PutTogether3x3Matrix -pl
python extract_scene.py old_projects/eola/footnote.py ShowMatrixVectorMultiplication -pl
python extract_scene.py old_projects/eola/footnote.py ShowMatrixMultiplication -pl
python extract_scene.py old_projects/eola/footnote2.py ColumnsRepresentBasisVectors -pl
python extract_scene.py old_projects/eola/footnote2.py Symbolic2To3DTransform -pl
python extract_scene.py old_projects/eola/footnote2.py OutputIn3dWords -pl
python extract_scene.py old_projects/eola/footnote2.py OutputIn3d -pl
python extract_scene.py old_projects/eola/footnote2.py ShowSideBySide2dTo3d -pl
python extract_scene.py old_projects/eola/footnote2.py AnimationLaziness -pl
python extract_scene.py old_projects/eola/footnote2.py DescribeColumnsInSpecificTransformation -pl
python extract_scene.py old_projects/eola/footnote2.py CountRowsAndColumns -pl
python extract_scene.py old_projects/eola/footnote2.py WriteColumnSpaceDefinition -pl
python extract_scene.py old_projects/eola/footnote2.py MatrixInTheWild -pl
python extract_scene.py old_projects/eola/footnote2.py ThreeDToTwoDInput -pl
python extract_scene.py old_projects/eola/footnote2.py ThreeDToTwoDInputWords -pl
python extract_scene.py old_projects/eola/footnote2.py ThreeDToTwoDSideBySide -pl
python extract_scene.py old_projects/eola/footnote2.py Symbolic2To1DTransform -pl
python extract_scene.py old_projects/eola/thumbnails.py Chapter1 -pl
python extract_scene.py old_projects/eola/thumbnails.py Chapter9 -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py EulersFormulaWords -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py TheTheoremWords -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py ProofAtLastWords -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py DualSpanningTreeWords -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py PreferOtherProofDialogue -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py PlanarGraphDefinition -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py FacebookLogo -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py FacebookGraphAsAbstractSet -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py ListOfCorrespondances -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py TwoPropertiesOfSpanningTree -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py TreeCountFormula -pl
python extract_scene.py old_projects/eulers_characteristic_formula.py FinalSum -pl
python extract_scene.py old_projects/fractal_dimension.py KochTest -pl
python extract_scene.py old_projects/fractal_dimension.py SierpinskiTest -pl
python extract_scene.py old_projects/fractal_dimension.py IntroduceVonKochCurve -pl
python extract_scene.py old_projects/fractal_dimension.py SelfSimilarFractalsAsSubset -pl
python extract_scene.py old_projects/fractal_dimension.py ConstrastSmoothAndFractal -pl
python extract_scene.py old_projects/fractal_dimension.py InfiniteKochZoom -pl
python extract_scene.py old_projects/fractal_dimension.py ShowIdealizations -pl
python extract_scene.py old_projects/fractal_dimension.py ExamplesOfDimension -pl
python extract_scene.py old_projects/fractal_dimension.py FractalDimensionIsNonsense -pl
python extract_scene.py old_projects/fractal_dimension.py DimensionForNaturalNumbers -pl
python extract_scene.py old_projects/fractal_dimension.py Show2DPlanein3D -pl
python extract_scene.py old_projects/fractal_dimension.py ShowCubeIn3D -pl
python extract_scene.py old_projects/fractal_dimension.py FourSelfSimilarShapes -pl
python extract_scene.py old_projects/fractal_dimension.py BreakUpCubeIn3D -pl
python extract_scene.py old_projects/fractal_dimension.py BrokenUpCubeIn3D -pl
python extract_scene.py old_projects/fractal_dimension.py GeneralWordForMeasurement -pl
python extract_scene.py old_projects/fractal_dimension.py ScaledLineMass -pl
python extract_scene.py old_projects/fractal_dimension.py FormCubeFromSubcubesIn3D -pl
python extract_scene.py old_projects/fractal_dimension.py ShowSierpinskiCurve -pl
python extract_scene.py old_projects/fractal_dimension.py FractionalAnalogOfLengthAndArea -pl
python extract_scene.py old_projects/fractal_dimension.py DimensionOfKoch -pl
python extract_scene.py old_projects/fractal_dimension.py ShowSeveralSelfSimilarityDimensions -pl
python extract_scene.py old_projects/fractal_dimension.py SeparateFractals -pl
python extract_scene.py old_projects/fractal_dimension.py ShowDiskScaling -pl
python extract_scene.py old_projects/fractal_dimension.py BoxCountingScene -pl
python extract_scene.py old_projects/fractal_dimension.py GiveShapeAndPonder -pl
python extract_scene.py old_projects/fractal_dimension.py RoughnessAndFractionalDimension -pl
python extract_scene.py old_projects/fractal_dimension.py SmoothHilbertZoom -pl
python extract_scene.py old_projects/fractal_dimension.py ZoomInOnBritain -pl
python extract_scene.py old_projects/fractal_dimension.py NoteTheConstantSlope -pl
python extract_scene.py old_projects/fractal_dimension.py FromHandwavyToQuantitative -pl
python extract_scene.py old_projects/fractal_dimension.py IfBritainWasEventuallySmooth -pl
python extract_scene.py old_projects/fractal_dimension.py CompareBritainAndNorway -pl
python extract_scene.py old_projects/fractal_dimension.py CompareOceansLabels -pl
python extract_scene.py old_projects/fractal_dimension.py CompareOceans -pl
python extract_scene.py old_projects/fractal_dimension.py FractalNonFractalFlowChart -pl
python extract_scene.py old_projects/generate_logo.py LogoGeneration -pl
python extract_scene.py old_projects/gradient.py ShowFunction -pl
python extract_scene.py old_projects/gradient.py TakePartialDerivatives -pl
python extract_scene.py old_projects/gradient.py ShowDerivativeAtExamplePoint -pl
python extract_scene.py old_projects/hanoi.py IntroduceKeith -pl
python extract_scene.py old_projects/hanoi.py KeithShowingBinary -pl
python extract_scene.py old_projects/hanoi.py RecursionTime -pl
python extract_scene.py old_projects/hanoi.py KeithSaysBigToSmall -pl
python extract_scene.py old_projects/hanoi.py CodeThisUp -pl
python extract_scene.py old_projects/hanoi.py NoRoomForInefficiency -pl
python extract_scene.py old_projects/hanoi.py WhyDoesBinaryAchieveThis -pl
python extract_scene.py old_projects/hanoi.py BothAreSelfSimilar -pl
python extract_scene.py old_projects/hanoi.py StillRecruse -pl
python extract_scene.py old_projects/hanoi.py KeithAsksAboutConfigurations -pl
python extract_scene.py old_projects/hanoi.py SierpinskiGraphScene -pl
python extract_scene.py old_projects/hanoi.py MentionFinalAnimation -pl
python extract_scene.py old_projects/hanoi.py PatreonThanks -pl
python extract_scene.py old_projects/highD.py MathIsATease -pl
python extract_scene.py old_projects/highD.py CircleToPairsOfPoints -pl
python extract_scene.py old_projects/hilbert/fractal_porn.py FromKochToSpaceFilling -pl
python extract_scene.py old_projects/hilbert/section1.py PostponePhilosophizing -pl
python extract_scene.py old_projects/hilbert/section1.py GrowHilbertWithName -pl
python extract_scene.py old_projects/hilbert/section1.py SectionOne -pl
python extract_scene.py old_projects/hilbert/section1.py WriteSomeSoftware -pl
python extract_scene.py old_projects/hilbert/section1.py ImageToSound -pl
python extract_scene.py old_projects/hilbert/section1.py LinksInDescription -pl
python extract_scene.py old_projects/hilbert/section1.py ImageDataIsTwoDimensional -pl
python extract_scene.py old_projects/hilbert/section1.py SoundDataIsOneDimensional -pl
python extract_scene.py old_projects/hilbert/section1.py GridOfPixels -pl
python extract_scene.py old_projects/hilbert/section1.py ShowFrequencySpace -pl
python extract_scene.py old_projects/hilbert/section1.py AssociatePixelWithFrequency -pl
python extract_scene.py old_projects/hilbert/section1.py ListenToAllPixels -pl
python extract_scene.py old_projects/hilbert/section1.py LayAsideSpeculation -pl
python extract_scene.py old_projects/hilbert/section1.py RandomMapping -pl
python extract_scene.py old_projects/hilbert/section1.py DataScrambledAnyway -pl
python extract_scene.py old_projects/hilbert/section1.py LeverageExistingIntuitions -pl
python extract_scene.py old_projects/hilbert/section1.py ThinkInTermsOfReverseMapping -pl
python extract_scene.py old_projects/hilbert/section1.py WeaveLineThroughPixels -pl
python extract_scene.py old_projects/hilbert/section1.py WellPlayedGameOfSnake -pl
python extract_scene.py old_projects/hilbert/section1.py TellMathematicianFriend -pl
python extract_scene.py old_projects/hilbert/section1.py Order1PseudoHilbertCurve -pl
python extract_scene.py old_projects/hilbert/section1.py Order2PseudoHilbertCurve -pl
python extract_scene.py old_projects/hilbert/section1.py Order3PseudoHilbertCurve -pl
python extract_scene.py old_projects/hilbert/section1.py GrowToOrder8PseudoHilbertCurve -pl
python extract_scene.py old_projects/hilbert/section1.py UseOrder8 -pl
python extract_scene.py old_projects/hilbert/section1.py HilbertBetterThanSnakeQ -pl
python extract_scene.py old_projects/hilbert/section1.py ImagineItWorks -pl
python extract_scene.py old_projects/hilbert/section1.py RandyWithHeadphones -pl
python extract_scene.py old_projects/hilbert/section1.py IncreaseResolution -pl
python extract_scene.py old_projects/hilbert/section1.py IncreasingResolutionWithSnakeCurve -pl
python extract_scene.py old_projects/hilbert/section1.py TrackSpecificCurvePoint -pl
python extract_scene.py old_projects/hilbert/section1.py NeedToRelearn -pl
python extract_scene.py old_projects/hilbert/section2.py SectionTwo -pl
python extract_scene.py old_projects/hilbert/section2.py HilbertCurveIsPerfect -pl
python extract_scene.py old_projects/hilbert/section2.py AskMathematicianFriend -pl
python extract_scene.py old_projects/hilbert/section2.py TimeLineAboutSpaceFilling -pl
python extract_scene.py old_projects/hilbert/section2.py NotPixelatedSpace -pl
python extract_scene.py old_projects/hilbert/section2.py HistoryOfDiscover -pl
python extract_scene.py old_projects/hilbert/section2.py DefinitionOfCurve -pl
python extract_scene.py old_projects/hilbert/section2.py PseudoHilbertCurvesDontFillSpace -pl
python extract_scene.py old_projects/hilbert/section2.py HilbertCurveIsLimit -pl
python extract_scene.py old_projects/hilbert/section2.py DefiningCurves -pl
python extract_scene.py old_projects/hilbert/section2.py PseudoHilbertCurveAsFunctionExample -pl
python extract_scene.py old_projects/hilbert/section2.py ContinuityRequired -pl
python extract_scene.py old_projects/hilbert/section2.py FormalDefinitionOfContinuity -pl
python extract_scene.py old_projects/hilbert/section2.py FunctionIsContinuousText -pl
python extract_scene.py old_projects/hilbert/section2.py DefineActualHilbertCurveText -pl
python extract_scene.py old_projects/hilbert/section2.py ReliesOnWonderfulProperty -pl
python extract_scene.py old_projects/hilbert/section2.py WonderfulPropertyOfPseudoHilbertCurves -pl
python extract_scene.py old_projects/hilbert/section2.py FollowManyPoints -pl
python extract_scene.py old_projects/hilbert/section2.py FormalDefinitionOfHilbertCurve -pl
python extract_scene.py old_projects/hilbert/section2.py CouldNotDefineForSnakeCurve -pl
python extract_scene.py old_projects/hilbert/section2.py ThreeThingsToProve -pl
python extract_scene.py old_projects/hilbert/section2.py TilingSpace -pl
python extract_scene.py old_projects/hilbert/section2.py ColorIntervals -pl
python extract_scene.py old_projects/hilbert/section3.py SectionThree -pl
python extract_scene.py old_projects/hilbert/section3.py InfiniteResultsFiniteWorld -pl
python extract_scene.py old_projects/hilbert/section3.py HilbertCurvesStayStable -pl
python extract_scene.py old_projects/hilbert/section3.py InfiniteObjectsEncapsulateFiniteObjects -pl
python extract_scene.py old_projects/hilbert/section3.py StatementRemovedFromReality -pl
python extract_scene.py old_projects/inventing_math.py IntroduceDivergentSum -pl
python extract_scene.py old_projects/inventing_math.py ClearlyNonsense -pl
python extract_scene.py old_projects/inventing_math.py OutlineOfVideo -pl
python extract_scene.py old_projects/inventing_math.py:# # class ReasonsForMakingVideo -pl
python extract_scene.py old_projects/inventing_math.py:# class DiscoverAndDefine -pl
python extract_scene.py old_projects/inventing_math.py YouAsMathematician -pl
python extract_scene.py old_projects/inventing_math.py DotsGettingCloser -pl
python extract_scene.py old_projects/inventing_math.py ZoomInOnInterval -pl
python extract_scene.py old_projects/inventing_math.py DanceDotOnInterval -pl
python extract_scene.py old_projects/inventing_math.py OrganizePartialSums -pl
python extract_scene.py old_projects/inventing_math.py SeeNumbersApproachOne -pl
python extract_scene.py old_projects/inventing_math.py OneAndInfiniteSumAreTheSameThing -pl
python extract_scene.py old_projects/inventing_math.py HowDoYouDefineInfiniteSums -pl
python extract_scene.py old_projects/inventing_math.py LessAboutNewThoughts -pl
python extract_scene.py old_projects/inventing_math.py ListOfPartialSums -pl
python extract_scene.py old_projects/inventing_math.py ShowDecreasingDistance -pl
python extract_scene.py old_projects/inventing_math.py CircleZoomInOnOne -pl
python extract_scene.py old_projects/inventing_math.py ZoomInOnOne -pl
python extract_scene.py old_projects/inventing_math.py DefineInfiniteSum -pl
python extract_scene.py old_projects/inventing_math.py YouJustInventedSomeMath -pl
python extract_scene.py old_projects/inventing_math.py SeekMoreGeneralTruths -pl
python extract_scene.py old_projects/inventing_math.py ChopIntervalInProportions -pl
python extract_scene.py old_projects/inventing_math.py PlugNumbersIntoRightside -pl
python extract_scene.py old_projects/inventing_math.py ListPartialDivergentSums -pl
python extract_scene.py old_projects/inventing_math.py NotARobot -pl
python extract_scene.py old_projects/inventing_math.py SumPowersOfTwoAnimation -pl
python extract_scene.py old_projects/inventing_math.py DistanceBetweenRationalNumbers -pl
python extract_scene.py old_projects/inventing_math.py NotTheOnlyWayToOrganize -pl
python extract_scene.py old_projects/inventing_math.py DistanceIsAFunction -pl
python extract_scene.py old_projects/inventing_math.py ShiftInvarianceNumberLine -pl
python extract_scene.py old_projects/inventing_math.py NameShiftInvarianceProperty -pl
python extract_scene.py old_projects/inventing_math.py TriangleInequality -pl
python extract_scene.py old_projects/inventing_math.py StruggleToFindFrameOfMind -pl
python extract_scene.py old_projects/inventing_math.py RoomsAndSubrooms -pl
python extract_scene.py old_projects/inventing_math.py RoomsAndSubroomsWithNumbers -pl
python extract_scene.py old_projects/inventing_math.py DeduceWhereNegativeOneFalls -pl
python extract_scene.py old_projects/inventing_math.py OtherRationalNumbers -pl
python extract_scene.py old_projects/inventing_math.py PAdicMetric -pl
python extract_scene.py old_projects/inventing_math.py FuzzyDiscoveryToNewMath -pl
python extract_scene.py old_projects/inventing_math.py DiscoveryAndInvention -pl
python extract_scene.py old_projects/inventing_math_images.py SimpleText -pl
python extract_scene.py old_projects/inventing_math_images.py SimpleTex -pl
python extract_scene.py old_projects/inventing_math_images.py OneMinusOnePoem -pl
python extract_scene.py old_projects/inventing_math_images.py DivergentSum -pl
python extract_scene.py old_projects/inventing_math_images.py PowersOfTwoSmall -pl
python extract_scene.py old_projects/inventing_math_images.py FinalSlide -pl
python extract_scene.py old_projects/lost_lecture.py ShowFullStory -pl
python extract_scene.py old_projects/lost_lecture.py FeynmanFame -pl
python extract_scene.py old_projects/lost_lecture.py TheMotionOfPlanets -pl
python extract_scene.py old_projects/lost_lecture.py FeynmanElementaryQuote -pl
python extract_scene.py old_projects/lost_lecture.py DrawEllipseOverlay -pl
python extract_scene.py old_projects/lost_lecture.py ShowEllipseDefiningProperty -pl
python extract_scene.py old_projects/lost_lecture.py FeynmanRecountingNewton -pl
python extract_scene.py old_projects/matrix_as_transform_2d.py TransformScene2D -pl
python extract_scene.py old_projects/matrix_as_transform_2d.py ExamplesOfNonlinearTwoDimensionalTransformations -pl
python extract_scene.py old_projects/matrix_as_transform_2d.py TrickyExamplesOfNonlinearTwoDimensionalTransformations -pl
python extract_scene.py old_projects/moser_main.py CircleScene -pl
python extract_scene.py old_projects/moser_main.py HardProblemsSimplerQuestions -pl
python extract_scene.py old_projects/moser_main.py GeneralPositionRule -pl
python extract_scene.py old_projects/moser_main.py IllustrateNChooseK -pl
python extract_scene.py old_projects/moser_main.py GraphsAndEulersFormulaJoke -pl
python extract_scene.py old_projects/moser_main.py FormulaRelatesToPowersOfTwo -pl
python extract_scene.py old_projects/moser_main.py RotatingPolyhedra -pl
python extract_scene.py old_projects/moser_main.py ExplainNChoose2Formula -pl
python extract_scene.py old_projects/moser_main.py ExplainNChoose4Formula -pl
python extract_scene.py old_projects/moser_main.py IntersectionChoppingExamples -pl
python extract_scene.py old_projects/music_and_measure.py TwoChallenges -pl
python extract_scene.py old_projects/music_and_measure.py ChallengeOne -pl
python extract_scene.py old_projects/music_and_measure.py JustByAnalyzingTheNumber -pl
python extract_scene.py old_projects/music_and_measure.py QuestionAndAnswer -pl
python extract_scene.py old_projects/music_and_measure.py PlaySimpleRatio -pl
python extract_scene.py old_projects/music_and_measure.py DecomposeMusicalNote -pl
python extract_scene.py old_projects/music_and_measure.py DecomposeTwoFrequencies -pl
python extract_scene.py old_projects/music_and_measure.py MostRationalsSoundBad -pl
python extract_scene.py old_projects/music_and_measure.py PatternInFrequencies -pl
python extract_scene.py old_projects/music_and_measure.py CompareFractionComplexity -pl
python extract_scene.py old_projects/music_and_measure.py IrrationalGang -pl
python extract_scene.py old_projects/music_and_measure.py ConstructPiano -pl
python extract_scene.py old_projects/music_and_measure.py PianoTuning -pl
python extract_scene.py old_projects/music_and_measure.py PowersOfTwelfthRoot -pl
python extract_scene.py old_projects/music_and_measure.py InterestingQuestion -pl
python extract_scene.py old_projects/music_and_measure.py SupposeThereIsASavant -pl
python extract_scene.py old_projects/music_and_measure.py ChallengeTwo -pl
python extract_scene.py old_projects/music_and_measure.py SurelyItsImpossible -pl
python extract_scene.py old_projects/music_and_measure.py PauseNow -pl
python extract_scene.py old_projects/music_and_measure.py OurSumCanBeArbitrarilySmall -pl
python extract_scene.py old_projects/music_and_measure.py ProofDoesNotEqualIntuition -pl
python extract_scene.py old_projects/music_and_measure.py VisualIntuition -pl
python extract_scene.py old_projects/music_and_measure.py SideNote -pl
python extract_scene.py old_projects/music_and_measure.py WhatDoesItLookLikeToBeOutside -pl
python extract_scene.py old_projects/music_and_measure.py NotCoveredMeansCacophonous -pl
python extract_scene.py old_projects/name_animation.py NameAnimationScene -pl
python extract_scene.py old_projects/nn/part1.py BrainAndHow -pl
python extract_scene.py old_projects/nn/part1.py WriteAProgram -pl
python extract_scene.py old_projects/nn/part1.py BreakDownName -pl
python extract_scene.py old_projects/nn/part1.py GenerallyLoopyPattern -pl
python extract_scene.py old_projects/nn/part1.py EdgeDetection -pl
python extract_scene.py old_projects/nn/part1.py SigmoidAppliedToVector -pl
python extract_scene.py old_projects/nn/part2.py ShowPlan -pl
python extract_scene.py old_projects/nn/part2.py BeginAndEndRecap -pl
python extract_scene.py old_projects/nn/part2.py BackpropComingLaterWords -pl
python extract_scene.py old_projects/nn/part2.py TrainingVsTestData -pl
python extract_scene.py old_projects/nn/part2.py MNistDescription -pl
python extract_scene.py old_projects/nn/part2.py TwoVariableInputSpace -pl
python extract_scene.py old_projects/nn/part2.py GradientDescentAlgorithm -pl
python extract_scene.py old_projects/nn/part2.py GradientDescentName -pl
python extract_scene.py old_projects/nn/part2.py DotsInsert -pl
python extract_scene.py old_projects/nn/part2.py NonSpatialGradientIntuition -pl
python extract_scene.py old_projects/nn/part2.py SpinningVectorWithLabel -pl
python extract_scene.py old_projects/nn/part2.py TwoGradientInterpretationsIn2D -pl
python extract_scene.py old_projects/nn/part2.py ShiftingFocus -pl
python extract_scene.py old_projects/nn/part2.py ConvolutionalNetworkPreview -pl
python extract_scene.py old_projects/nn/part2.py RandomlyLabeledImageData -pl
python extract_scene.py old_projects/nn/part2.py IntroduceDeepNetwork -pl
python extract_scene.py old_projects/nn/part2.py ManyMinimaWords -pl
python extract_scene.py old_projects/nn/part3.py LayOutPlan -pl
python extract_scene.py old_projects/nn/part3.py WriteHebbian -pl
python extract_scene.py old_projects/nn/part3.py ConstructGradientFromAllTrainingExamples -pl
python extract_scene.py old_projects/nn/part3.py OpenCloseSGD -pl
python extract_scene.py old_projects/nn/part3.py OrganizeDataIntoMiniBatches -pl
python extract_scene.py old_projects/nn/part3.py EOCWrapper -pl
python extract_scene.py old_projects/nn/part3.py LayersOfComplexity -pl
python extract_scene.py old_projects/pi_day.py AnalysisQuote -pl
python extract_scene.py old_projects/pi_day.py BernoulliQuote -pl
python extract_scene.py old_projects/pi_day.py EulerSignature -pl
python extract_scene.py old_projects/pi_day.py EulerWrites628 -pl
python extract_scene.py old_projects/pi_day.py HeroAndVillain -pl
python extract_scene.py old_projects/pi_day.py AnalysisQuote -pl
python extract_scene.py old_projects/pi_day.py EulerThinking -pl
python extract_scene.py old_projects/playground_counting_in_binary.py EdgeDetection -pl
python extract_scene.py old_projects/playground_counting_in_binary.py BufferedCounting -pl
python extract_scene.py old_projects/playground_counting_in_binary.py ClearLeftSide -pl
python extract_scene.py old_projects/playground_counting_in_binary.py DraggedPixels -pl
python extract_scene.py old_projects/playground_counting_in_binary.py SaveEachNumber -pl
python extract_scene.py old_projects/playground_counting_in_binary.py ShowCounting -pl
python extract_scene.py old_projects/playground_counting_in_binary.py ShowFrameNum -pl
python extract_scene.py old_projects/putnam.py TwoDCase -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawPointsReference -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawTriangle -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawAllThreeSquares -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawOnlyABSquares -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawNakedCSqurae -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawCSquareWithAllTraingles -pl
python extract_scene.py old_projects/pythagorean_proof.py ZoomInOnTroublePoint -pl
python extract_scene.py old_projects/pythagorean_proof.py DrawTriangleWithAngles -pl
python extract_scene.py old_projects/tattoo.py Credit -pl
python extract_scene.py old_projects/tau_poem.py HappyTauDayWords -pl
python extract_scene.py old_projects/tau_poem.py TauPoem -pl
python extract_scene.py old_projects/triangle_of_power/end.py NotationReflectsMath -pl
python extract_scene.py old_projects/triangle_of_power/end.py InYourOwnNotes -pl
python extract_scene.py old_projects/triangle_of_power/intro.py Notation -pl
python extract_scene.py old_projects/triangle_of_power/intro.py WhatTheHell -pl
python extract_scene.py old_projects/triangle_of_power/intro.py PascalsCollision -pl
python extract_scene.py old_projects/triangle_of_power/triangle.py ShowRule -pl
python extract_scene.py old_projects/triangle_of_power/triangle.py SixSixSix -pl
python extract_scene.py old_projects/triangle_of_power/triangle.py ConstantLowerRight -pl
python extract_scene.py old_projects/triples.py VisualizeZSquared -pl
python extract_scene.py old_projects/uncertainty.py TwoCarsAtRedLight -pl
python extract_scene.py old_projects/uncertainty.py IntroduceDopplerRadar -pl
python extract_scene.py old_projects/uncertainty.py RadarOperatorUncertainty -pl
python extract_scene.py old_projects/uncertainty.py SummarizeFourierTradeoffForDoppler -pl
python extract_scene.py old_projects/uncertainty.py IntroduceDeBroglie -pl
python extract_scene.py old_projects/uncertainty.py MinutPhysicsWrapper -pl
python extract_scene.py old_projects/uncertainty.py OneLevelDeeper -pl
python extract_scene.py old_projects/uncertainty.py PuzzleStatement -pl
python extract_scene.py old_projects/wallis.py MentionJohnWallis -pl
python extract_scene.py old_projects/waves.py WriteCurlEquations -pl
python extract_scene.py old_projects/waves.py ShowVectorEquation -pl
python extract_scene.py old_projects/waves.py Footnote -pl
python extract_scene.py old_projects/wcat.py NotHelpful -pl
python extract_scene.py old_projects/wcat.py PatreonThanks -pl
python extract_scene.py old_projects/wcat.py CreditTWo -pl
python extract_scene.py old_projects/WindingNumber.py ColorMappedByFuncScene -pl
python extract_scene.py old_projects/WindingNumber.py:# class BFTScene -pl
python extract_scene.py old_projects/WindingNumber_G.py AllOfTheVideos -pl
python extract_scene.py old_projects/WindingNumber_G.py MentionQAndA -pl
python extract_scene.py old_projects/WindingNumber_G.py PatreonScroll -pl
python extract_scene.py old_projects/zeta.py ComplexExponentiation -pl
python extract_scene.py old_projects/zeta.py DiscussSumOfNaturals -pl
python extract_scene.py old_projects/zeta.py FinalAnimationTease -pl
python extract_scene.py old_projects/zeta.py PatreonThanks -pl
python extract_scene.py old_projects/zeta.py CreditTwo -pl
python extract_scene.py once_useful_constructs/arithmetic.py RearrangeEquation -pl
python extract_scene.py once_useful_constructs/graph_theory.py DiscreteGraphScene -pl
python extract_scene.py once_useful_constructs/matrix_multiplication.py NumericalMatrixMultiplication -pl
python extract_scene.py scene/scene_from_video.py SceneFromVideo -pl
